/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Components: typeof import('./src/components/index.vue')['default']
    copy: typeof import('./src/components/layout/hearder copy/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Footer: typeof import('./src/components/layout/footer/index.vue')['default']
    Header: typeof import('./src/components/layout/header/index.vue')['default']
    Hearder: typeof import('./src/components/layout/hearder/index.vue')['default']
    HOME: typeof import('./src/components/HOME.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    Main: typeof import('./src/components/layout/main/index.vue')['default']
    PageHeader: typeof import('./src/components/page-header/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/svg-icon.vue')['default']
    Test: typeof import('./src/components/test.vue')['default']
  }
}
